import { IContrat } from 'app/shared/model/contrat.model';
import { IAbsence } from 'app/shared/model/absence.model';
import { IPrime } from 'app/shared/model/prime.model';
import { IFichePaie } from 'app/shared/model/fiche-paie.model';
import { IHeuresSupplementaires } from 'app/shared/model/heures-supplementaires.model';
import { INoteDeFrais } from 'app/shared/model/note-de-frais.model';
import { IAvanceRappelSalaire } from 'app/shared/model/avance-rappel-salaire.model';
import { IAutresVariable } from 'app/shared/model/autres-variable.model';
import { IDocument } from 'app/shared/model/document.model';
import { IDpae } from 'app/shared/model/dpae.model';

export interface IEmploye {
  id?: number;
  matricule?: string;
  civilite?: string;
  nomNaissance?: string;
  nomUsage?: string;
  prenom?: string;
  dateNaissance?: string;
  villeNaissance?: string;
  departementNaissance?: string;
  paysNaisance?: string;
  numeroSecuriteSociale?: string;
  email?: string;
  telephoneFix?: string;
  telephonePortable?: string;
  fax?: string;
  salaireHoraire?: number;
  salaireBrutMensuelle?: number;
  heuresMensuelle?: number;
  categorie?: string;
  poste?: string;
  dateEmbauche?: string;
  dateSortie?: string;
  periodeEssai?: number;
  situationFamiliale?: string;
  enfantsACharge?: number;
  listeContrats?: IContrat[];
  listeAbsences?: IAbsence[];
  listePrimes?: IPrime[];
  listeFichePaies?: IFichePaie[];
  listeHeureSupplementaires?: IHeuresSupplementaires[];
  listeNoteDeFrais?: INoteDeFrais[];
  listeAvanceRappelSalaires?: IAvanceRappelSalaire[];
  listeAutresVariables?: IAutresVariable[];
  listeDocuments?: IDocument[];
  listeDpaes?: IDpae[];
  statutEmployeId?: number;
  adresseId?: number;
  societeId?: number;
}

export const defaultValue: Readonly<IEmploye> = {};
